@EmployeeManagement.API_HostAddress = http://localhost:5100

GET {{EmployeeManagement.API_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{EmployeeManagement.API_HostAddress}}/api/Employee
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "salary": -500, 
  "departmentId": 1
}

###
GET {{EmployeeManagement.API_HostAddress}}/api/employee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYm9zcyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzg4NTMwNjIzLCJpc3MiOiJFbXBsb3llZU1hbmFnZW1lbnRBUEkiLCJhdWQiOiJFbXBsb3llZU1hbmFnZW1lbnRGcm9udGVuZCJ9.NJWRiPf18ULeewW43udcYx4xmfGoAE-fzyH_Uqh4rAw
Content-Type: application/json



###
POST {{EmployeeManagement.API_HostAddress}}/api/Auth/login
Content-Type: application/json

{
  "username": "boss",
  "password": "SuperSecretPassword!"
}
 
###
DELETE {{EmployeeManagement.API_HostAddress}}/api/Employee/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYm9zcyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzg4ODU0MDQ0LCJpc3MiOiJFbXBsb3llZU1hbmFnZW1lbnRBUEkiLCJhdWQiOiJFbXBsb3llZU1hbmFnZW1lbnRGcm9udGVuZCJ9.PgEDYnFAzOdd-3m-9vSxz1aoYoIASdw-2TqGXjrt5bI

###
POST {{EmployeeManagement.API_HostAddress}}/api/Employee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYm9zcyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzg4ODU0MDQ0LCJpc3MiOiJFbXBsb3llZU1hbmFnZW1lbnRBUEkiLCJhdWQiOiJFbXBsb3llZU1hbmFnZW1lbnRGcm9udGVuZCJ9.PgEDYnFAzOdd-3m-9vSxz1aoYoIASdw-2TqGXjrt5bI
Content-Type: application/json

{
  "firstName": "Lavindu",
  "lastName": "Sandeepa",
  "email": "lavindu.sandeepa@example.com",
  "salary": 85000,
  "departmentId": 1
}